// Code generated by go-swagger; DO NOT EDIT.

package filesystemlayout

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFunc1Params creates a new Func1Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFunc1Params() *Func1Params {
	return &Func1Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewFunc1ParamsWithTimeout creates a new Func1Params object
// with the ability to set a timeout on a request.
func NewFunc1ParamsWithTimeout(timeout time.Duration) *Func1Params {
	return &Func1Params{
		timeout: timeout,
	}
}

// NewFunc1ParamsWithContext creates a new Func1Params object
// with the ability to set a context for a request.
func NewFunc1ParamsWithContext(ctx context.Context) *Func1Params {
	return &Func1Params{
		Context: ctx,
	}
}

// NewFunc1ParamsWithHTTPClient creates a new Func1Params object
// with the ability to set a custom HTTPClient for a request.
func NewFunc1ParamsWithHTTPClient(client *http.Client) *Func1Params {
	return &Func1Params{
		HTTPClient: client,
	}
}

/* Func1Params contains all the parameters to send to the API endpoint
   for the func1 operation.

   Typically these are written to a http.Request.
*/
type Func1Params struct {

	/* ID.

	   identifier of the filesystemlayout
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the func1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Func1Params) WithDefaults() *Func1Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the func1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Func1Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the func1 params
func (o *Func1Params) WithTimeout(timeout time.Duration) *Func1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the func1 params
func (o *Func1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the func1 params
func (o *Func1Params) WithContext(ctx context.Context) *Func1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the func1 params
func (o *Func1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the func1 params
func (o *Func1Params) WithHTTPClient(client *http.Client) *Func1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the func1 params
func (o *Func1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the func1 params
func (o *Func1Params) WithID(id string) *Func1Params {
	o.SetID(id)
	return o
}

// SetID adds the id to the func1 params
func (o *Func1Params) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *Func1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
