// Code generated by go-swagger; DO NOT EDIT.

package filesystemlayout

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/metal-stack/metal-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// ListFilesystemLayoutsReader is a Reader for the ListFilesystemLayouts structure.
type ListFilesystemLayoutsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListFilesystemLayoutsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListFilesystemLayoutsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListFilesystemLayoutsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListFilesystemLayoutsOK creates a ListFilesystemLayoutsOK with default headers values
func NewListFilesystemLayoutsOK() *ListFilesystemLayoutsOK {
	return &ListFilesystemLayoutsOK{}
}

/*
	ListFilesystemLayoutsOK describes a response with status code 200, with default header values.

OK
*/
type ListFilesystemLayoutsOK struct {
	Payload []*models.V1FilesystemLayoutResponse
}

func (o *ListFilesystemLayoutsOK) Error() string {
	return fmt.Sprintf("[GET /v1/filesystemlayout][%d] listFilesystemLayoutsOK  %+v", 200, o.Payload)
}
func (o *ListFilesystemLayoutsOK) GetPayload() []*models.V1FilesystemLayoutResponse {
	return o.Payload
}

func (o *ListFilesystemLayoutsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListFilesystemLayoutsDefault creates a ListFilesystemLayoutsDefault with default headers values
func NewListFilesystemLayoutsDefault(code int) *ListFilesystemLayoutsDefault {
	return &ListFilesystemLayoutsDefault{
		_statusCode: code,
	}
}

/*
	ListFilesystemLayoutsDefault describes a response with status code -1, with default header values.

Error
*/
type ListFilesystemLayoutsDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// Code gets the status code for the list filesystem layouts default response
func (o *ListFilesystemLayoutsDefault) Code() int {
	return o._statusCode
}

func (o *ListFilesystemLayoutsDefault) Error() string {
	return fmt.Sprintf("[GET /v1/filesystemlayout][%d] listFilesystemLayouts default  %+v", o._statusCode, o.Payload)
}
func (o *ListFilesystemLayoutsDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *ListFilesystemLayoutsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
