// Code generated by go-swagger; DO NOT EDIT.

package filesystemlayout

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/metal-stack/metal-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// TryFilesystemLayoutReader is a Reader for the TryFilesystemLayout structure.
type TryFilesystemLayoutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TryFilesystemLayoutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTryFilesystemLayoutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewTryFilesystemLayoutDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewTryFilesystemLayoutOK creates a TryFilesystemLayoutOK with default headers values
func NewTryFilesystemLayoutOK() *TryFilesystemLayoutOK {
	return &TryFilesystemLayoutOK{}
}

/*
TryFilesystemLayoutOK describes a response with status code 200, with default header values.

OK
*/
type TryFilesystemLayoutOK struct {
	Payload *models.V1FilesystemLayoutResponse
}

// IsSuccess returns true when this try filesystem layout o k response has a 2xx status code
func (o *TryFilesystemLayoutOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this try filesystem layout o k response has a 3xx status code
func (o *TryFilesystemLayoutOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this try filesystem layout o k response has a 4xx status code
func (o *TryFilesystemLayoutOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this try filesystem layout o k response has a 5xx status code
func (o *TryFilesystemLayoutOK) IsServerError() bool {
	return false
}

// IsCode returns true when this try filesystem layout o k response a status code equal to that given
func (o *TryFilesystemLayoutOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the try filesystem layout o k response
func (o *TryFilesystemLayoutOK) Code() int {
	return 200
}

func (o *TryFilesystemLayoutOK) Error() string {
	return fmt.Sprintf("[POST /v1/filesystemlayout/try][%d] tryFilesystemLayoutOK  %+v", 200, o.Payload)
}

func (o *TryFilesystemLayoutOK) String() string {
	return fmt.Sprintf("[POST /v1/filesystemlayout/try][%d] tryFilesystemLayoutOK  %+v", 200, o.Payload)
}

func (o *TryFilesystemLayoutOK) GetPayload() *models.V1FilesystemLayoutResponse {
	return o.Payload
}

func (o *TryFilesystemLayoutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1FilesystemLayoutResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTryFilesystemLayoutDefault creates a TryFilesystemLayoutDefault with default headers values
func NewTryFilesystemLayoutDefault(code int) *TryFilesystemLayoutDefault {
	return &TryFilesystemLayoutDefault{
		_statusCode: code,
	}
}

/*
TryFilesystemLayoutDefault describes a response with status code -1, with default header values.

Error
*/
type TryFilesystemLayoutDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// IsSuccess returns true when this try filesystem layout default response has a 2xx status code
func (o *TryFilesystemLayoutDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this try filesystem layout default response has a 3xx status code
func (o *TryFilesystemLayoutDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this try filesystem layout default response has a 4xx status code
func (o *TryFilesystemLayoutDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this try filesystem layout default response has a 5xx status code
func (o *TryFilesystemLayoutDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this try filesystem layout default response a status code equal to that given
func (o *TryFilesystemLayoutDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the try filesystem layout default response
func (o *TryFilesystemLayoutDefault) Code() int {
	return o._statusCode
}

func (o *TryFilesystemLayoutDefault) Error() string {
	return fmt.Sprintf("[POST /v1/filesystemlayout/try][%d] tryFilesystemLayout default  %+v", o._statusCode, o.Payload)
}

func (o *TryFilesystemLayoutDefault) String() string {
	return fmt.Sprintf("[POST /v1/filesystemlayout/try][%d] tryFilesystemLayout default  %+v", o._statusCode, o.Payload)
}

func (o *TryFilesystemLayoutDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *TryFilesystemLayoutDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
