// Code generated by go-swagger; DO NOT EDIT.

package filesystemlayout

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/metal-stack/metal-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// TryFilesystemLayoutReader is a Reader for the TryFilesystemLayout structure.
type TryFilesystemLayoutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TryFilesystemLayoutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTryFilesystemLayoutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 409:
		result := NewTryFilesystemLayoutConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewTryFilesystemLayoutDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewTryFilesystemLayoutOK creates a TryFilesystemLayoutOK with default headers values
func NewTryFilesystemLayoutOK() *TryFilesystemLayoutOK {
	return &TryFilesystemLayoutOK{}
}

/* TryFilesystemLayoutOK describes a response with status code 200, with default header values.

OK
*/
type TryFilesystemLayoutOK struct {
	Payload *models.V1FilesystemLayoutResponse
}

func (o *TryFilesystemLayoutOK) Error() string {
	return fmt.Sprintf("[POST /v1/filesystemlayout/try][%d] tryFilesystemLayoutOK  %+v", 200, o.Payload)
}
func (o *TryFilesystemLayoutOK) GetPayload() *models.V1FilesystemLayoutResponse {
	return o.Payload
}

func (o *TryFilesystemLayoutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1FilesystemLayoutResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTryFilesystemLayoutConflict creates a TryFilesystemLayoutConflict with default headers values
func NewTryFilesystemLayoutConflict() *TryFilesystemLayoutConflict {
	return &TryFilesystemLayoutConflict{}
}

/* TryFilesystemLayoutConflict describes a response with status code 409, with default header values.

Conflict
*/
type TryFilesystemLayoutConflict struct {
	Payload *httperrors.HTTPErrorResponse
}

func (o *TryFilesystemLayoutConflict) Error() string {
	return fmt.Sprintf("[POST /v1/filesystemlayout/try][%d] tryFilesystemLayoutConflict  %+v", 409, o.Payload)
}
func (o *TryFilesystemLayoutConflict) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *TryFilesystemLayoutConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTryFilesystemLayoutDefault creates a TryFilesystemLayoutDefault with default headers values
func NewTryFilesystemLayoutDefault(code int) *TryFilesystemLayoutDefault {
	return &TryFilesystemLayoutDefault{
		_statusCode: code,
	}
}

/* TryFilesystemLayoutDefault describes a response with status code -1, with default header values.

Error
*/
type TryFilesystemLayoutDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// Code gets the status code for the try filesystem layout default response
func (o *TryFilesystemLayoutDefault) Code() int {
	return o._statusCode
}

func (o *TryFilesystemLayoutDefault) Error() string {
	return fmt.Sprintf("[POST /v1/filesystemlayout/try][%d] tryFilesystemLayout default  %+v", o._statusCode, o.Payload)
}
func (o *TryFilesystemLayoutDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *TryFilesystemLayoutDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
