// Code generated by go-swagger; DO NOT EDIT.

package filesystemlayout

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/metal-stack/metal-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// UpdateFilesystemLayoutReader is a Reader for the UpdateFilesystemLayout structure.
type UpdateFilesystemLayoutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateFilesystemLayoutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateFilesystemLayoutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 409:
		result := NewUpdateFilesystemLayoutConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewUpdateFilesystemLayoutDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateFilesystemLayoutOK creates a UpdateFilesystemLayoutOK with default headers values
func NewUpdateFilesystemLayoutOK() *UpdateFilesystemLayoutOK {
	return &UpdateFilesystemLayoutOK{}
}

/*
UpdateFilesystemLayoutOK describes a response with status code 200, with default header values.

OK
*/
type UpdateFilesystemLayoutOK struct {
	Payload *models.V1FilesystemLayoutResponse
}

// IsSuccess returns true when this update filesystem layout o k response has a 2xx status code
func (o *UpdateFilesystemLayoutOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update filesystem layout o k response has a 3xx status code
func (o *UpdateFilesystemLayoutOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update filesystem layout o k response has a 4xx status code
func (o *UpdateFilesystemLayoutOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update filesystem layout o k response has a 5xx status code
func (o *UpdateFilesystemLayoutOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update filesystem layout o k response a status code equal to that given
func (o *UpdateFilesystemLayoutOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update filesystem layout o k response
func (o *UpdateFilesystemLayoutOK) Code() int {
	return 200
}

func (o *UpdateFilesystemLayoutOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/filesystemlayout][%d] updateFilesystemLayoutOK %s", 200, payload)
}

func (o *UpdateFilesystemLayoutOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/filesystemlayout][%d] updateFilesystemLayoutOK %s", 200, payload)
}

func (o *UpdateFilesystemLayoutOK) GetPayload() *models.V1FilesystemLayoutResponse {
	return o.Payload
}

func (o *UpdateFilesystemLayoutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1FilesystemLayoutResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateFilesystemLayoutConflict creates a UpdateFilesystemLayoutConflict with default headers values
func NewUpdateFilesystemLayoutConflict() *UpdateFilesystemLayoutConflict {
	return &UpdateFilesystemLayoutConflict{}
}

/*
UpdateFilesystemLayoutConflict describes a response with status code 409, with default header values.

Conflict
*/
type UpdateFilesystemLayoutConflict struct {
	Payload *httperrors.HTTPErrorResponse
}

// IsSuccess returns true when this update filesystem layout conflict response has a 2xx status code
func (o *UpdateFilesystemLayoutConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update filesystem layout conflict response has a 3xx status code
func (o *UpdateFilesystemLayoutConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update filesystem layout conflict response has a 4xx status code
func (o *UpdateFilesystemLayoutConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this update filesystem layout conflict response has a 5xx status code
func (o *UpdateFilesystemLayoutConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this update filesystem layout conflict response a status code equal to that given
func (o *UpdateFilesystemLayoutConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the update filesystem layout conflict response
func (o *UpdateFilesystemLayoutConflict) Code() int {
	return 409
}

func (o *UpdateFilesystemLayoutConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/filesystemlayout][%d] updateFilesystemLayoutConflict %s", 409, payload)
}

func (o *UpdateFilesystemLayoutConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/filesystemlayout][%d] updateFilesystemLayoutConflict %s", 409, payload)
}

func (o *UpdateFilesystemLayoutConflict) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *UpdateFilesystemLayoutConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateFilesystemLayoutDefault creates a UpdateFilesystemLayoutDefault with default headers values
func NewUpdateFilesystemLayoutDefault(code int) *UpdateFilesystemLayoutDefault {
	return &UpdateFilesystemLayoutDefault{
		_statusCode: code,
	}
}

/*
UpdateFilesystemLayoutDefault describes a response with status code -1, with default header values.

Error
*/
type UpdateFilesystemLayoutDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// IsSuccess returns true when this update filesystem layout default response has a 2xx status code
func (o *UpdateFilesystemLayoutDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this update filesystem layout default response has a 3xx status code
func (o *UpdateFilesystemLayoutDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this update filesystem layout default response has a 4xx status code
func (o *UpdateFilesystemLayoutDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this update filesystem layout default response has a 5xx status code
func (o *UpdateFilesystemLayoutDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this update filesystem layout default response a status code equal to that given
func (o *UpdateFilesystemLayoutDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the update filesystem layout default response
func (o *UpdateFilesystemLayoutDefault) Code() int {
	return o._statusCode
}

func (o *UpdateFilesystemLayoutDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/filesystemlayout][%d] updateFilesystemLayout default %s", o._statusCode, payload)
}

func (o *UpdateFilesystemLayoutDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/filesystemlayout][%d] updateFilesystemLayout default %s", o._statusCode, payload)
}

func (o *UpdateFilesystemLayoutDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *UpdateFilesystemLayoutDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
