// Code generated by go-swagger; DO NOT EDIT.

package switch_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteSwitchParams creates a new DeleteSwitchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteSwitchParams() *DeleteSwitchParams {
	return &DeleteSwitchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSwitchParamsWithTimeout creates a new DeleteSwitchParams object
// with the ability to set a timeout on a request.
func NewDeleteSwitchParamsWithTimeout(timeout time.Duration) *DeleteSwitchParams {
	return &DeleteSwitchParams{
		timeout: timeout,
	}
}

// NewDeleteSwitchParamsWithContext creates a new DeleteSwitchParams object
// with the ability to set a context for a request.
func NewDeleteSwitchParamsWithContext(ctx context.Context) *DeleteSwitchParams {
	return &DeleteSwitchParams{
		Context: ctx,
	}
}

// NewDeleteSwitchParamsWithHTTPClient creates a new DeleteSwitchParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteSwitchParamsWithHTTPClient(client *http.Client) *DeleteSwitchParams {
	return &DeleteSwitchParams{
		HTTPClient: client,
	}
}

/* DeleteSwitchParams contains all the parameters to send to the API endpoint
   for the delete switch operation.

   Typically these are written to a http.Request.
*/
type DeleteSwitchParams struct {

	/* ID.

	   identifier of the switch
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete switch params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteSwitchParams) WithDefaults() *DeleteSwitchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete switch params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteSwitchParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete switch params
func (o *DeleteSwitchParams) WithTimeout(timeout time.Duration) *DeleteSwitchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete switch params
func (o *DeleteSwitchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete switch params
func (o *DeleteSwitchParams) WithContext(ctx context.Context) *DeleteSwitchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete switch params
func (o *DeleteSwitchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete switch params
func (o *DeleteSwitchParams) WithHTTPClient(client *http.Client) *DeleteSwitchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete switch params
func (o *DeleteSwitchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete switch params
func (o *DeleteSwitchParams) WithID(id string) *DeleteSwitchParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete switch params
func (o *DeleteSwitchParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSwitchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
