// Code generated by go-swagger; DO NOT EDIT.

package tenant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/metal-stack/metal-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// DeleteTenantReader is a Reader for the DeleteTenant structure.
type DeleteTenantReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteTenantReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteTenantOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteTenantDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteTenantOK creates a DeleteTenantOK with default headers values
func NewDeleteTenantOK() *DeleteTenantOK {
	return &DeleteTenantOK{}
}

/*
DeleteTenantOK describes a response with status code 200, with default header values.

OK
*/
type DeleteTenantOK struct {
	Payload *models.V1TenantResponse
}

// IsSuccess returns true when this delete tenant o k response has a 2xx status code
func (o *DeleteTenantOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete tenant o k response has a 3xx status code
func (o *DeleteTenantOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete tenant o k response has a 4xx status code
func (o *DeleteTenantOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete tenant o k response has a 5xx status code
func (o *DeleteTenantOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete tenant o k response a status code equal to that given
func (o *DeleteTenantOK) IsCode(code int) bool {
	return code == 200
}

func (o *DeleteTenantOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/tenant/{id}][%d] deleteTenantOK  %+v", 200, o.Payload)
}

func (o *DeleteTenantOK) String() string {
	return fmt.Sprintf("[DELETE /v1/tenant/{id}][%d] deleteTenantOK  %+v", 200, o.Payload)
}

func (o *DeleteTenantOK) GetPayload() *models.V1TenantResponse {
	return o.Payload
}

func (o *DeleteTenantOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1TenantResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteTenantDefault creates a DeleteTenantDefault with default headers values
func NewDeleteTenantDefault(code int) *DeleteTenantDefault {
	return &DeleteTenantDefault{
		_statusCode: code,
	}
}

/*
DeleteTenantDefault describes a response with status code -1, with default header values.

Error
*/
type DeleteTenantDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// Code gets the status code for the delete tenant default response
func (o *DeleteTenantDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this delete tenant default response has a 2xx status code
func (o *DeleteTenantDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete tenant default response has a 3xx status code
func (o *DeleteTenantDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete tenant default response has a 4xx status code
func (o *DeleteTenantDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete tenant default response has a 5xx status code
func (o *DeleteTenantDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete tenant default response a status code equal to that given
func (o *DeleteTenantDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *DeleteTenantDefault) Error() string {
	return fmt.Sprintf("[DELETE /v1/tenant/{id}][%d] deleteTenant default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteTenantDefault) String() string {
	return fmt.Sprintf("[DELETE /v1/tenant/{id}][%d] deleteTenant default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteTenantDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *DeleteTenantDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
