// Code generated by go-swagger; DO NOT EDIT.

package tenant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/metal-stack/metal-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// UpdateTenantReader is a Reader for the UpdateTenant structure.
type UpdateTenantReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateTenantReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateTenantOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 412:
		result := NewUpdateTenantPreconditionFailed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewUpdateTenantDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateTenantOK creates a UpdateTenantOK with default headers values
func NewUpdateTenantOK() *UpdateTenantOK {
	return &UpdateTenantOK{}
}

/*
UpdateTenantOK describes a response with status code 200, with default header values.

Updated
*/
type UpdateTenantOK struct {
	Payload *models.V1TenantResponse
}

// IsSuccess returns true when this update tenant o k response has a 2xx status code
func (o *UpdateTenantOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update tenant o k response has a 3xx status code
func (o *UpdateTenantOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update tenant o k response has a 4xx status code
func (o *UpdateTenantOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update tenant o k response has a 5xx status code
func (o *UpdateTenantOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update tenant o k response a status code equal to that given
func (o *UpdateTenantOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update tenant o k response
func (o *UpdateTenantOK) Code() int {
	return 200
}

func (o *UpdateTenantOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/tenant][%d] updateTenantOK %s", 200, payload)
}

func (o *UpdateTenantOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/tenant][%d] updateTenantOK %s", 200, payload)
}

func (o *UpdateTenantOK) GetPayload() *models.V1TenantResponse {
	return o.Payload
}

func (o *UpdateTenantOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1TenantResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateTenantPreconditionFailed creates a UpdateTenantPreconditionFailed with default headers values
func NewUpdateTenantPreconditionFailed() *UpdateTenantPreconditionFailed {
	return &UpdateTenantPreconditionFailed{}
}

/*
UpdateTenantPreconditionFailed describes a response with status code 412, with default header values.

OptimisticLock
*/
type UpdateTenantPreconditionFailed struct {
	Payload *httperrors.HTTPErrorResponse
}

// IsSuccess returns true when this update tenant precondition failed response has a 2xx status code
func (o *UpdateTenantPreconditionFailed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update tenant precondition failed response has a 3xx status code
func (o *UpdateTenantPreconditionFailed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update tenant precondition failed response has a 4xx status code
func (o *UpdateTenantPreconditionFailed) IsClientError() bool {
	return true
}

// IsServerError returns true when this update tenant precondition failed response has a 5xx status code
func (o *UpdateTenantPreconditionFailed) IsServerError() bool {
	return false
}

// IsCode returns true when this update tenant precondition failed response a status code equal to that given
func (o *UpdateTenantPreconditionFailed) IsCode(code int) bool {
	return code == 412
}

// Code gets the status code for the update tenant precondition failed response
func (o *UpdateTenantPreconditionFailed) Code() int {
	return 412
}

func (o *UpdateTenantPreconditionFailed) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/tenant][%d] updateTenantPreconditionFailed %s", 412, payload)
}

func (o *UpdateTenantPreconditionFailed) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/tenant][%d] updateTenantPreconditionFailed %s", 412, payload)
}

func (o *UpdateTenantPreconditionFailed) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *UpdateTenantPreconditionFailed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateTenantDefault creates a UpdateTenantDefault with default headers values
func NewUpdateTenantDefault(code int) *UpdateTenantDefault {
	return &UpdateTenantDefault{
		_statusCode: code,
	}
}

/*
UpdateTenantDefault describes a response with status code -1, with default header values.

Error
*/
type UpdateTenantDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// IsSuccess returns true when this update tenant default response has a 2xx status code
func (o *UpdateTenantDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this update tenant default response has a 3xx status code
func (o *UpdateTenantDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this update tenant default response has a 4xx status code
func (o *UpdateTenantDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this update tenant default response has a 5xx status code
func (o *UpdateTenantDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this update tenant default response a status code equal to that given
func (o *UpdateTenantDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the update tenant default response
func (o *UpdateTenantDefault) Code() int {
	return o._statusCode
}

func (o *UpdateTenantDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/tenant][%d] updateTenant default %s", o._statusCode, payload)
}

func (o *UpdateTenantDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/tenant][%d] updateTenant default %s", o._statusCode, payload)
}

func (o *UpdateTenantDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *UpdateTenantDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
