// Code generated by go-swagger; DO NOT EDIT.

package sizeimageconstraint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/metal-stack/metal-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// DeleteSizeImageConstraintReader is a Reader for the DeleteSizeImageConstraint structure.
type DeleteSizeImageConstraintReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSizeImageConstraintReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteSizeImageConstraintOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteSizeImageConstraintDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteSizeImageConstraintOK creates a DeleteSizeImageConstraintOK with default headers values
func NewDeleteSizeImageConstraintOK() *DeleteSizeImageConstraintOK {
	return &DeleteSizeImageConstraintOK{}
}

/* DeleteSizeImageConstraintOK describes a response with status code 200, with default header values.

OK
*/
type DeleteSizeImageConstraintOK struct {
	Payload *models.V1SizeImageConstraintResponse
}

func (o *DeleteSizeImageConstraintOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/sizeimageconstraint/{id}][%d] deleteSizeImageConstraintOK  %+v", 200, o.Payload)
}
func (o *DeleteSizeImageConstraintOK) GetPayload() *models.V1SizeImageConstraintResponse {
	return o.Payload
}

func (o *DeleteSizeImageConstraintOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1SizeImageConstraintResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSizeImageConstraintDefault creates a DeleteSizeImageConstraintDefault with default headers values
func NewDeleteSizeImageConstraintDefault(code int) *DeleteSizeImageConstraintDefault {
	return &DeleteSizeImageConstraintDefault{
		_statusCode: code,
	}
}

/* DeleteSizeImageConstraintDefault describes a response with status code -1, with default header values.

Error
*/
type DeleteSizeImageConstraintDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// Code gets the status code for the delete size image constraint default response
func (o *DeleteSizeImageConstraintDefault) Code() int {
	return o._statusCode
}

func (o *DeleteSizeImageConstraintDefault) Error() string {
	return fmt.Sprintf("[DELETE /v1/sizeimageconstraint/{id}][%d] deleteSizeImageConstraint default  %+v", o._statusCode, o.Payload)
}
func (o *DeleteSizeImageConstraintDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *DeleteSizeImageConstraintDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
