// Code generated by go-swagger; DO NOT EDIT.

package machine

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/metal-stack/metal-go/models"
)

// NewUpdateMachineParams creates a new UpdateMachineParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateMachineParams() *UpdateMachineParams {
	return &UpdateMachineParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateMachineParamsWithTimeout creates a new UpdateMachineParams object
// with the ability to set a timeout on a request.
func NewUpdateMachineParamsWithTimeout(timeout time.Duration) *UpdateMachineParams {
	return &UpdateMachineParams{
		timeout: timeout,
	}
}

// NewUpdateMachineParamsWithContext creates a new UpdateMachineParams object
// with the ability to set a context for a request.
func NewUpdateMachineParamsWithContext(ctx context.Context) *UpdateMachineParams {
	return &UpdateMachineParams{
		Context: ctx,
	}
}

// NewUpdateMachineParamsWithHTTPClient creates a new UpdateMachineParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateMachineParamsWithHTTPClient(client *http.Client) *UpdateMachineParams {
	return &UpdateMachineParams{
		HTTPClient: client,
	}
}

/* UpdateMachineParams contains all the parameters to send to the API endpoint
   for the update machine operation.

   Typically these are written to a http.Request.
*/
type UpdateMachineParams struct {

	// Body.
	Body *models.V1MachineUpdateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update machine params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateMachineParams) WithDefaults() *UpdateMachineParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update machine params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateMachineParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update machine params
func (o *UpdateMachineParams) WithTimeout(timeout time.Duration) *UpdateMachineParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update machine params
func (o *UpdateMachineParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update machine params
func (o *UpdateMachineParams) WithContext(ctx context.Context) *UpdateMachineParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update machine params
func (o *UpdateMachineParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update machine params
func (o *UpdateMachineParams) WithHTTPClient(client *http.Client) *UpdateMachineParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update machine params
func (o *UpdateMachineParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update machine params
func (o *UpdateMachineParams) WithBody(body *models.V1MachineUpdateRequest) *UpdateMachineParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update machine params
func (o *UpdateMachineParams) SetBody(body *models.V1MachineUpdateRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateMachineParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
