// Code generated by mockery v2.7.4. DO NOT EDIT.

package ip

import (
	runtime "github.com/go-openapi/runtime"
	mock "github.com/stretchr/testify/mock"
)

// ClientOption is an autogenerated mock type for the ClientOption type
type ClientOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *ClientOption) Execute(_a0 *runtime.ClientOperation) {
	_m.Called(_a0)
}
