// Code generated by go-swagger; DO NOT EDIT.

package size

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/metal-stack/metal-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// FindSizeImageConstraintsReader is a Reader for the FindSizeImageConstraints structure.
type FindSizeImageConstraintsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindSizeImageConstraintsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindSizeImageConstraintsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewFindSizeImageConstraintsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewFindSizeImageConstraintsOK creates a FindSizeImageConstraintsOK with default headers values
func NewFindSizeImageConstraintsOK() *FindSizeImageConstraintsOK {
	return &FindSizeImageConstraintsOK{}
}

/* FindSizeImageConstraintsOK describes a response with status code 200, with default header values.

OK
*/
type FindSizeImageConstraintsOK struct {
	Payload *models.V1SizeResponse
}

func (o *FindSizeImageConstraintsOK) Error() string {
	return fmt.Sprintf("[GET /v1/size/sizeimageconstraints/{id}][%d] findSizeImageConstraintsOK  %+v", 200, o.Payload)
}
func (o *FindSizeImageConstraintsOK) GetPayload() *models.V1SizeResponse {
	return o.Payload
}

func (o *FindSizeImageConstraintsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1SizeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindSizeImageConstraintsDefault creates a FindSizeImageConstraintsDefault with default headers values
func NewFindSizeImageConstraintsDefault(code int) *FindSizeImageConstraintsDefault {
	return &FindSizeImageConstraintsDefault{
		_statusCode: code,
	}
}

/* FindSizeImageConstraintsDefault describes a response with status code -1, with default header values.

Error
*/
type FindSizeImageConstraintsDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// Code gets the status code for the find size image constraints default response
func (o *FindSizeImageConstraintsDefault) Code() int {
	return o._statusCode
}

func (o *FindSizeImageConstraintsDefault) Error() string {
	return fmt.Sprintf("[GET /v1/size/sizeimageconstraints/{id}][%d] findSizeImageConstraints default  %+v", o._statusCode, o.Payload)
}
func (o *FindSizeImageConstraintsDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *FindSizeImageConstraintsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
