// Code generated by go-swagger; DO NOT EDIT.

package size

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/metal-stack/metal-go/api/models"
)

// NewListSizeReservationsParams creates a new ListSizeReservationsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListSizeReservationsParams() *ListSizeReservationsParams {
	return &ListSizeReservationsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListSizeReservationsParamsWithTimeout creates a new ListSizeReservationsParams object
// with the ability to set a timeout on a request.
func NewListSizeReservationsParamsWithTimeout(timeout time.Duration) *ListSizeReservationsParams {
	return &ListSizeReservationsParams{
		timeout: timeout,
	}
}

// NewListSizeReservationsParamsWithContext creates a new ListSizeReservationsParams object
// with the ability to set a context for a request.
func NewListSizeReservationsParamsWithContext(ctx context.Context) *ListSizeReservationsParams {
	return &ListSizeReservationsParams{
		Context: ctx,
	}
}

// NewListSizeReservationsParamsWithHTTPClient creates a new ListSizeReservationsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListSizeReservationsParamsWithHTTPClient(client *http.Client) *ListSizeReservationsParams {
	return &ListSizeReservationsParams{
		HTTPClient: client,
	}
}

/*
ListSizeReservationsParams contains all the parameters to send to the API endpoint

	for the list size reservations operation.

	Typically these are written to a http.Request.
*/
type ListSizeReservationsParams struct {

	// Body.
	Body *models.V1SizeReservationListRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list size reservations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListSizeReservationsParams) WithDefaults() *ListSizeReservationsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list size reservations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListSizeReservationsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list size reservations params
func (o *ListSizeReservationsParams) WithTimeout(timeout time.Duration) *ListSizeReservationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list size reservations params
func (o *ListSizeReservationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list size reservations params
func (o *ListSizeReservationsParams) WithContext(ctx context.Context) *ListSizeReservationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list size reservations params
func (o *ListSizeReservationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list size reservations params
func (o *ListSizeReservationsParams) WithHTTPClient(client *http.Client) *ListSizeReservationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list size reservations params
func (o *ListSizeReservationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the list size reservations params
func (o *ListSizeReservationsParams) WithBody(body *models.V1SizeReservationListRequest) *ListSizeReservationsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the list size reservations params
func (o *ListSizeReservationsParams) SetBody(body *models.V1SizeReservationListRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ListSizeReservationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
