// Code generated by go-swagger; DO NOT EDIT.

package size

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/metal-stack/metal-go/api/models"
)

// NewUpdateSizeReservationParams creates a new UpdateSizeReservationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateSizeReservationParams() *UpdateSizeReservationParams {
	return &UpdateSizeReservationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateSizeReservationParamsWithTimeout creates a new UpdateSizeReservationParams object
// with the ability to set a timeout on a request.
func NewUpdateSizeReservationParamsWithTimeout(timeout time.Duration) *UpdateSizeReservationParams {
	return &UpdateSizeReservationParams{
		timeout: timeout,
	}
}

// NewUpdateSizeReservationParamsWithContext creates a new UpdateSizeReservationParams object
// with the ability to set a context for a request.
func NewUpdateSizeReservationParamsWithContext(ctx context.Context) *UpdateSizeReservationParams {
	return &UpdateSizeReservationParams{
		Context: ctx,
	}
}

// NewUpdateSizeReservationParamsWithHTTPClient creates a new UpdateSizeReservationParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateSizeReservationParamsWithHTTPClient(client *http.Client) *UpdateSizeReservationParams {
	return &UpdateSizeReservationParams{
		HTTPClient: client,
	}
}

/*
UpdateSizeReservationParams contains all the parameters to send to the API endpoint

	for the update size reservation operation.

	Typically these are written to a http.Request.
*/
type UpdateSizeReservationParams struct {

	// Body.
	Body *models.V1SizeReservationUpdateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update size reservation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateSizeReservationParams) WithDefaults() *UpdateSizeReservationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update size reservation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateSizeReservationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update size reservation params
func (o *UpdateSizeReservationParams) WithTimeout(timeout time.Duration) *UpdateSizeReservationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update size reservation params
func (o *UpdateSizeReservationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update size reservation params
func (o *UpdateSizeReservationParams) WithContext(ctx context.Context) *UpdateSizeReservationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update size reservation params
func (o *UpdateSizeReservationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update size reservation params
func (o *UpdateSizeReservationParams) WithHTTPClient(client *http.Client) *UpdateSizeReservationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update size reservation params
func (o *UpdateSizeReservationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update size reservation params
func (o *UpdateSizeReservationParams) WithBody(body *models.V1SizeReservationUpdateRequest) *UpdateSizeReservationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update size reservation params
func (o *UpdateSizeReservationParams) SetBody(body *models.V1SizeReservationUpdateRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateSizeReservationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
