// Code generated by go-swagger; DO NOT EDIT.

package partition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/metal-stack/metal-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// ListPartitionsReader is a Reader for the ListPartitions structure.
type ListPartitionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListPartitionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListPartitionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListPartitionsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListPartitionsOK creates a ListPartitionsOK with default headers values
func NewListPartitionsOK() *ListPartitionsOK {
	return &ListPartitionsOK{}
}

/*
ListPartitionsOK describes a response with status code 200, with default header values.

OK
*/
type ListPartitionsOK struct {
	Payload []*models.V1PartitionResponse
}

// IsSuccess returns true when this list partitions o k response has a 2xx status code
func (o *ListPartitionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list partitions o k response has a 3xx status code
func (o *ListPartitionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list partitions o k response has a 4xx status code
func (o *ListPartitionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list partitions o k response has a 5xx status code
func (o *ListPartitionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list partitions o k response a status code equal to that given
func (o *ListPartitionsOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListPartitionsOK) Error() string {
	return fmt.Sprintf("[GET /v1/partition][%d] listPartitionsOK  %+v", 200, o.Payload)
}

func (o *ListPartitionsOK) String() string {
	return fmt.Sprintf("[GET /v1/partition][%d] listPartitionsOK  %+v", 200, o.Payload)
}

func (o *ListPartitionsOK) GetPayload() []*models.V1PartitionResponse {
	return o.Payload
}

func (o *ListPartitionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPartitionsDefault creates a ListPartitionsDefault with default headers values
func NewListPartitionsDefault(code int) *ListPartitionsDefault {
	return &ListPartitionsDefault{
		_statusCode: code,
	}
}

/*
ListPartitionsDefault describes a response with status code -1, with default header values.

Error
*/
type ListPartitionsDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// Code gets the status code for the list partitions default response
func (o *ListPartitionsDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this list partitions default response has a 2xx status code
func (o *ListPartitionsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list partitions default response has a 3xx status code
func (o *ListPartitionsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list partitions default response has a 4xx status code
func (o *ListPartitionsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list partitions default response has a 5xx status code
func (o *ListPartitionsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list partitions default response a status code equal to that given
func (o *ListPartitionsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ListPartitionsDefault) Error() string {
	return fmt.Sprintf("[GET /v1/partition][%d] listPartitions default  %+v", o._statusCode, o.Payload)
}

func (o *ListPartitionsDefault) String() string {
	return fmt.Sprintf("[GET /v1/partition][%d] listPartitions default  %+v", o._statusCode, o.Payload)
}

func (o *ListPartitionsDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *ListPartitionsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
