// Code generated by go-swagger; DO NOT EDIT.

package partition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/metal-stack/metal-go/api/models"
)

// NewUpdatePartitionParams creates a new UpdatePartitionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdatePartitionParams() *UpdatePartitionParams {
	return &UpdatePartitionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdatePartitionParamsWithTimeout creates a new UpdatePartitionParams object
// with the ability to set a timeout on a request.
func NewUpdatePartitionParamsWithTimeout(timeout time.Duration) *UpdatePartitionParams {
	return &UpdatePartitionParams{
		timeout: timeout,
	}
}

// NewUpdatePartitionParamsWithContext creates a new UpdatePartitionParams object
// with the ability to set a context for a request.
func NewUpdatePartitionParamsWithContext(ctx context.Context) *UpdatePartitionParams {
	return &UpdatePartitionParams{
		Context: ctx,
	}
}

// NewUpdatePartitionParamsWithHTTPClient creates a new UpdatePartitionParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdatePartitionParamsWithHTTPClient(client *http.Client) *UpdatePartitionParams {
	return &UpdatePartitionParams{
		HTTPClient: client,
	}
}

/*
UpdatePartitionParams contains all the parameters to send to the API endpoint

	for the update partition operation.

	Typically these are written to a http.Request.
*/
type UpdatePartitionParams struct {

	// Body.
	Body *models.V1PartitionUpdateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update partition params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdatePartitionParams) WithDefaults() *UpdatePartitionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update partition params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdatePartitionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update partition params
func (o *UpdatePartitionParams) WithTimeout(timeout time.Duration) *UpdatePartitionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update partition params
func (o *UpdatePartitionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update partition params
func (o *UpdatePartitionParams) WithContext(ctx context.Context) *UpdatePartitionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update partition params
func (o *UpdatePartitionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update partition params
func (o *UpdatePartitionParams) WithHTTPClient(client *http.Client) *UpdatePartitionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update partition params
func (o *UpdatePartitionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update partition params
func (o *UpdatePartitionParams) WithBody(body *models.V1PartitionUpdateRequest) *UpdatePartitionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update partition params
func (o *UpdatePartitionParams) SetBody(body *models.V1PartitionUpdateRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdatePartitionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
