// Code generated by go-swagger; DO NOT EDIT.

package filesystemlayout

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/metal-stack/metal-go/models"
)

// NewMatchFilesystemLayoutParams creates a new MatchFilesystemLayoutParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMatchFilesystemLayoutParams() *MatchFilesystemLayoutParams {
	return &MatchFilesystemLayoutParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMatchFilesystemLayoutParamsWithTimeout creates a new MatchFilesystemLayoutParams object
// with the ability to set a timeout on a request.
func NewMatchFilesystemLayoutParamsWithTimeout(timeout time.Duration) *MatchFilesystemLayoutParams {
	return &MatchFilesystemLayoutParams{
		timeout: timeout,
	}
}

// NewMatchFilesystemLayoutParamsWithContext creates a new MatchFilesystemLayoutParams object
// with the ability to set a context for a request.
func NewMatchFilesystemLayoutParamsWithContext(ctx context.Context) *MatchFilesystemLayoutParams {
	return &MatchFilesystemLayoutParams{
		Context: ctx,
	}
}

// NewMatchFilesystemLayoutParamsWithHTTPClient creates a new MatchFilesystemLayoutParams object
// with the ability to set a custom HTTPClient for a request.
func NewMatchFilesystemLayoutParamsWithHTTPClient(client *http.Client) *MatchFilesystemLayoutParams {
	return &MatchFilesystemLayoutParams{
		HTTPClient: client,
	}
}

/* MatchFilesystemLayoutParams contains all the parameters to send to the API endpoint
   for the match filesystem layout operation.

   Typically these are written to a http.Request.
*/
type MatchFilesystemLayoutParams struct {

	// Body.
	Body *models.V1FilesystemLayoutMatchRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the match filesystem layout params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MatchFilesystemLayoutParams) WithDefaults() *MatchFilesystemLayoutParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the match filesystem layout params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MatchFilesystemLayoutParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the match filesystem layout params
func (o *MatchFilesystemLayoutParams) WithTimeout(timeout time.Duration) *MatchFilesystemLayoutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the match filesystem layout params
func (o *MatchFilesystemLayoutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the match filesystem layout params
func (o *MatchFilesystemLayoutParams) WithContext(ctx context.Context) *MatchFilesystemLayoutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the match filesystem layout params
func (o *MatchFilesystemLayoutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the match filesystem layout params
func (o *MatchFilesystemLayoutParams) WithHTTPClient(client *http.Client) *MatchFilesystemLayoutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the match filesystem layout params
func (o *MatchFilesystemLayoutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the match filesystem layout params
func (o *MatchFilesystemLayoutParams) WithBody(body *models.V1FilesystemLayoutMatchRequest) *MatchFilesystemLayoutParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the match filesystem layout params
func (o *MatchFilesystemLayoutParams) SetBody(body *models.V1FilesystemLayoutMatchRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *MatchFilesystemLayoutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
