// Code generated by go-swagger; DO NOT EDIT.

package ip

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/metal-pod/metal-go/api/models"
)

// NewAnnounceIPParams creates a new AnnounceIPParams object
// with the default values initialized.
func NewAnnounceIPParams() *AnnounceIPParams {
	var ()
	return &AnnounceIPParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAnnounceIPParamsWithTimeout creates a new AnnounceIPParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAnnounceIPParamsWithTimeout(timeout time.Duration) *AnnounceIPParams {
	var ()
	return &AnnounceIPParams{

		timeout: timeout,
	}
}

// NewAnnounceIPParamsWithContext creates a new AnnounceIPParams object
// with the default values initialized, and the ability to set a context for a request
func NewAnnounceIPParamsWithContext(ctx context.Context) *AnnounceIPParams {
	var ()
	return &AnnounceIPParams{

		Context: ctx,
	}
}

// NewAnnounceIPParamsWithHTTPClient creates a new AnnounceIPParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAnnounceIPParamsWithHTTPClient(client *http.Client) *AnnounceIPParams {
	var ()
	return &AnnounceIPParams{
		HTTPClient: client,
	}
}

/*AnnounceIPParams contains all the parameters to send to the API endpoint
for the announce IP operation typically these are written to a http.Request
*/
type AnnounceIPParams struct {

	/*Body*/
	Body *models.V1IPAnnounceRequest
	/*IP
	  ip to try to announce

	*/
	IP string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the announce IP params
func (o *AnnounceIPParams) WithTimeout(timeout time.Duration) *AnnounceIPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the announce IP params
func (o *AnnounceIPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the announce IP params
func (o *AnnounceIPParams) WithContext(ctx context.Context) *AnnounceIPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the announce IP params
func (o *AnnounceIPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the announce IP params
func (o *AnnounceIPParams) WithHTTPClient(client *http.Client) *AnnounceIPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the announce IP params
func (o *AnnounceIPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the announce IP params
func (o *AnnounceIPParams) WithBody(body *models.V1IPAnnounceRequest) *AnnounceIPParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the announce IP params
func (o *AnnounceIPParams) SetBody(body *models.V1IPAnnounceRequest) {
	o.Body = body
}

// WithIP adds the ip to the announce IP params
func (o *AnnounceIPParams) WithIP(ip string) *AnnounceIPParams {
	o.SetIP(ip)
	return o
}

// SetIP adds the ip to the announce IP params
func (o *AnnounceIPParams) SetIP(ip string) {
	o.IP = ip
}

// WriteToRequest writes these params to a swagger request
func (o *AnnounceIPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param ip
	if err := r.SetPathParam("ip", o.IP); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
