// Code generated by go-swagger; DO NOT EDIT.

package ip

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/metal-stack/metal-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// ListIPsReader is a Reader for the ListIPs structure.
type ListIPsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListIPsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListIPsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListIPsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListIPsOK creates a ListIPsOK with default headers values
func NewListIPsOK() *ListIPsOK {
	return &ListIPsOK{}
}

/*
ListIPsOK describes a response with status code 200, with default header values.

OK
*/
type ListIPsOK struct {
	Payload []*models.V1IPResponse
}

// IsSuccess returns true when this list i ps o k response has a 2xx status code
func (o *ListIPsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list i ps o k response has a 3xx status code
func (o *ListIPsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list i ps o k response has a 4xx status code
func (o *ListIPsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list i ps o k response has a 5xx status code
func (o *ListIPsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list i ps o k response a status code equal to that given
func (o *ListIPsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list i ps o k response
func (o *ListIPsOK) Code() int {
	return 200
}

func (o *ListIPsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/ip][%d] listIPsOK %s", 200, payload)
}

func (o *ListIPsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/ip][%d] listIPsOK %s", 200, payload)
}

func (o *ListIPsOK) GetPayload() []*models.V1IPResponse {
	return o.Payload
}

func (o *ListIPsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListIPsDefault creates a ListIPsDefault with default headers values
func NewListIPsDefault(code int) *ListIPsDefault {
	return &ListIPsDefault{
		_statusCode: code,
	}
}

/*
ListIPsDefault describes a response with status code -1, with default header values.

Error
*/
type ListIPsDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// IsSuccess returns true when this list i ps default response has a 2xx status code
func (o *ListIPsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list i ps default response has a 3xx status code
func (o *ListIPsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list i ps default response has a 4xx status code
func (o *ListIPsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list i ps default response has a 5xx status code
func (o *ListIPsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list i ps default response a status code equal to that given
func (o *ListIPsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list i ps default response
func (o *ListIPsDefault) Code() int {
	return o._statusCode
}

func (o *ListIPsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/ip][%d] listIPs default %s", o._statusCode, payload)
}

func (o *ListIPsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/ip][%d] listIPs default %s", o._statusCode, payload)
}

func (o *ListIPsDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *ListIPsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
