// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DatastoreSwitchSearchQuery datastore switch search query
//
// swagger:model datastore.SwitchSearchQuery
type DatastoreSwitchSearchQuery struct {

	// id
	ID string `json:"id,omitempty" yaml:"id,omitempty"`

	// name
	Name string `json:"name,omitempty" yaml:"name,omitempty"`

	// osvendor
	Osvendor string `json:"osvendor,omitempty" yaml:"osvendor,omitempty"`

	// osversion
	Osversion string `json:"osversion,omitempty" yaml:"osversion,omitempty"`

	// partitionid
	Partitionid string `json:"partitionid,omitempty" yaml:"partitionid,omitempty"`

	// rackid
	Rackid string `json:"rackid,omitempty" yaml:"rackid,omitempty"`
}

// Validate validates this datastore switch search query
func (m *DatastoreSwitchSearchQuery) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this datastore switch search query based on context it is used
func (m *DatastoreSwitchSearchQuery) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DatastoreSwitchSearchQuery) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DatastoreSwitchSearchQuery) UnmarshalBinary(b []byte) error {
	var res DatastoreSwitchSearchQuery
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
