// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1DiskPartition v1 disk partition
//
// swagger:model v1.DiskPartition
type V1DiskPartition struct {

	// the gpt partition table type of this partition
	// Required: true
	Gpttype *string `json:"gpttype"`

	// optional label for this this partition
	// Required: true
	Label *string `json:"label"`

	// partition number, will be appended to partitionprefix to create the final devicename
	// Required: true
	Number *int64 `json:"number"`

	// size in mebibytes of this partition
	// Required: true
	Size *int64 `json:"size"`
}

// Validate validates this v1 disk partition
func (m *V1DiskPartition) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGpttype(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLabel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNumber(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSize(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1DiskPartition) validateGpttype(formats strfmt.Registry) error {

	if err := validate.Required("gpttype", "body", m.Gpttype); err != nil {
		return err
	}

	return nil
}

func (m *V1DiskPartition) validateLabel(formats strfmt.Registry) error {

	if err := validate.Required("label", "body", m.Label); err != nil {
		return err
	}

	return nil
}

func (m *V1DiskPartition) validateNumber(formats strfmt.Registry) error {

	if err := validate.Required("number", "body", m.Number); err != nil {
		return err
	}

	return nil
}

func (m *V1DiskPartition) validateSize(formats strfmt.Registry) error {

	if err := validate.Required("size", "body", m.Size); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this v1 disk partition based on context it is used
func (m *V1DiskPartition) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1DiskPartition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1DiskPartition) UnmarshalBinary(b []byte) error {
	var res V1DiskPartition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
