// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1FirewallCreateRequest v1 firewall create request
//
// swagger:model v1.FirewallCreateRequest
type V1FirewallCreateRequest struct {

	// a description for this entity
	Description string `json:"description,omitempty" yaml:"description,omitempty"`

	// the filesystemlayout id to assign to this machine
	Filesystemlayoutid string `json:"filesystemlayoutid,omitempty" yaml:"filesystemlayoutid,omitempty"`

	// optional egress and ingress firewall rules to deploy during firewall allocation
	FirewallRules *V1FirewallRules `json:"firewall_rules,omitempty" yaml:"firewall_rules,omitempty"`

	// the hostname for the allocated machine (defaults to metal)
	Hostname string `json:"hostname,omitempty" yaml:"hostname,omitempty"`

	// the image id to assign this machine to
	// Required: true
	Imageid *string `json:"imageid" yaml:"imageid"`

	// the ips to attach to this machine additionally
	Ips []string `json:"ips" yaml:"ips"`

	// a readable name for this entity
	Name string `json:"name,omitempty" yaml:"name,omitempty"`

	// the networks that this machine will be placed in.
	Networks []*V1MachineAllocationNetwork `json:"networks" yaml:"networks"`

	// the partition id to assign this machine to
	// Required: true
	Partitionid *string `json:"partitionid" yaml:"partitionid"`

	// by default machines are spread across the racks inside a partition for every project. if placement tags are provided, the machine candidate has an additional anti-affinity to other machines having the same tags
	PlacementTags []string `json:"placement_tags" yaml:"placement_tags"`

	// the project id to assign this machine to
	// Required: true
	Projectid *string `json:"projectid" yaml:"projectid"`

	// the size id to assign this machine to
	// Required: true
	Sizeid *string `json:"sizeid" yaml:"sizeid"`

	// the public ssh keys to access the machine with
	// Required: true
	SSHPubKeys []string `json:"ssh_pub_keys" yaml:"ssh_pub_keys"`

	// tags for this machine
	Tags []string `json:"tags" yaml:"tags"`

	// cloud-init.io compatible userdata must be base64 encoded
	UserData string `json:"user_data,omitempty" yaml:"user_data,omitempty"`

	// if this field is set, this specific machine will be allocated if it is not in available state and not currently allocated. this field overrules size and partition
	UUID string `json:"uuid,omitempty" yaml:"uuid,omitempty"`
}

// Validate validates this v1 firewall create request
func (m *V1FirewallCreateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFirewallRules(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateImageid(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNetworks(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePartitionid(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProjectid(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSizeid(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSSHPubKeys(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1FirewallCreateRequest) validateFirewallRules(formats strfmt.Registry) error {
	if swag.IsZero(m.FirewallRules) { // not required
		return nil
	}

	if m.FirewallRules != nil {
		if err := m.FirewallRules.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("firewall_rules")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("firewall_rules")
			}
			return err
		}
	}

	return nil
}

func (m *V1FirewallCreateRequest) validateImageid(formats strfmt.Registry) error {

	if err := validate.Required("imageid", "body", m.Imageid); err != nil {
		return err
	}

	return nil
}

func (m *V1FirewallCreateRequest) validateNetworks(formats strfmt.Registry) error {
	if swag.IsZero(m.Networks) { // not required
		return nil
	}

	for i := 0; i < len(m.Networks); i++ {
		if swag.IsZero(m.Networks[i]) { // not required
			continue
		}

		if m.Networks[i] != nil {
			if err := m.Networks[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("networks" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("networks" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *V1FirewallCreateRequest) validatePartitionid(formats strfmt.Registry) error {

	if err := validate.Required("partitionid", "body", m.Partitionid); err != nil {
		return err
	}

	return nil
}

func (m *V1FirewallCreateRequest) validateProjectid(formats strfmt.Registry) error {

	if err := validate.Required("projectid", "body", m.Projectid); err != nil {
		return err
	}

	return nil
}

func (m *V1FirewallCreateRequest) validateSizeid(formats strfmt.Registry) error {

	if err := validate.Required("sizeid", "body", m.Sizeid); err != nil {
		return err
	}

	return nil
}

func (m *V1FirewallCreateRequest) validateSSHPubKeys(formats strfmt.Registry) error {

	if err := validate.Required("ssh_pub_keys", "body", m.SSHPubKeys); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this v1 firewall create request based on the context it is used
func (m *V1FirewallCreateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFirewallRules(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateNetworks(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1FirewallCreateRequest) contextValidateFirewallRules(ctx context.Context, formats strfmt.Registry) error {

	if m.FirewallRules != nil {

		if swag.IsZero(m.FirewallRules) { // not required
			return nil
		}

		if err := m.FirewallRules.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("firewall_rules")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("firewall_rules")
			}
			return err
		}
	}

	return nil
}

func (m *V1FirewallCreateRequest) contextValidateNetworks(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Networks); i++ {

		if m.Networks[i] != nil {

			if swag.IsZero(m.Networks[i]) { // not required
				return nil
			}

			if err := m.Networks[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("networks" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("networks" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1FirewallCreateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1FirewallCreateRequest) UnmarshalBinary(b []byte) error {
	var res V1FirewallCreateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
