// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1MachineAvailableUpdates v1 machine available updates
//
// swagger:model v1.MachineAvailableUpdates
type V1MachineAvailableUpdates struct {

	// list of all available BIOS updates
	// Required: true
	Revisions []string `json:"revisions"`
}

// Validate validates this v1 machine available updates
func (m *V1MachineAvailableUpdates) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRevisions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1MachineAvailableUpdates) validateRevisions(formats strfmt.Registry) error {

	if err := validate.Required("revisions", "body", m.Revisions); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1MachineAvailableUpdates) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1MachineAvailableUpdates) UnmarshalBinary(b []byte) error {
	var res V1MachineAvailableUpdates
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
