// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1SizeSuggestRequest v1 size suggest request
//
// swagger:model v1.SizeSuggestRequest
type V1SizeSuggestRequest struct {

	// machineID to retrieve size suggestion for
	// Required: true
	MachineID *string `json:"machineID" yaml:"machineID"`
}

// Validate validates this v1 size suggest request
func (m *V1SizeSuggestRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMachineID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1SizeSuggestRequest) validateMachineID(formats strfmt.Registry) error {

	if err := validate.Required("machineID", "body", m.MachineID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this v1 size suggest request based on context it is used
func (m *V1SizeSuggestRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1SizeSuggestRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1SizeSuggestRequest) UnmarshalBinary(b []byte) error {
	var res V1SizeSuggestRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
