// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1SwitchBase A switch that can register at the api.
//
// swagger:model v1.SwitchBase
type V1SwitchBase struct {

	// the mode the switch currently has
	Mode string `json:"mode,omitempty" yaml:"mode,omitempty"`

	// the id of the rack in which this switch is located
	// Required: true
	RackID *string `json:"rack_id" yaml:"rack_id"`
}

// Validate validates this v1 switch base
func (m *V1SwitchBase) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRackID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1SwitchBase) validateRackID(formats strfmt.Registry) error {

	if err := validate.Required("rack_id", "body", m.RackID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this v1 switch base based on context it is used
func (m *V1SwitchBase) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1SwitchBase) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1SwitchBase) UnmarshalBinary(b []byte) error {
	var res V1SwitchBase
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
