// Code generated by go-swagger; DO NOT EDIT.

package machine

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/metal-stack/metal-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// AbortReinstallMachineReader is a Reader for the AbortReinstallMachine structure.
type AbortReinstallMachineReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AbortReinstallMachineReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAbortReinstallMachineOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAbortReinstallMachineDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAbortReinstallMachineOK creates a AbortReinstallMachineOK with default headers values
func NewAbortReinstallMachineOK() *AbortReinstallMachineOK {
	return &AbortReinstallMachineOK{}
}

/*
AbortReinstallMachineOK describes a response with status code 200, with default header values.

OK
*/
type AbortReinstallMachineOK struct {
	Payload *models.V1BootInfo
}

// IsSuccess returns true when this abort reinstall machine o k response has a 2xx status code
func (o *AbortReinstallMachineOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this abort reinstall machine o k response has a 3xx status code
func (o *AbortReinstallMachineOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this abort reinstall machine o k response has a 4xx status code
func (o *AbortReinstallMachineOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this abort reinstall machine o k response has a 5xx status code
func (o *AbortReinstallMachineOK) IsServerError() bool {
	return false
}

// IsCode returns true when this abort reinstall machine o k response a status code equal to that given
func (o *AbortReinstallMachineOK) IsCode(code int) bool {
	return code == 200
}

func (o *AbortReinstallMachineOK) Error() string {
	return fmt.Sprintf("[POST /v1/machine/{id}/abort-reinstall][%d] abortReinstallMachineOK  %+v", 200, o.Payload)
}

func (o *AbortReinstallMachineOK) String() string {
	return fmt.Sprintf("[POST /v1/machine/{id}/abort-reinstall][%d] abortReinstallMachineOK  %+v", 200, o.Payload)
}

func (o *AbortReinstallMachineOK) GetPayload() *models.V1BootInfo {
	return o.Payload
}

func (o *AbortReinstallMachineOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1BootInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAbortReinstallMachineDefault creates a AbortReinstallMachineDefault with default headers values
func NewAbortReinstallMachineDefault(code int) *AbortReinstallMachineDefault {
	return &AbortReinstallMachineDefault{
		_statusCode: code,
	}
}

/*
AbortReinstallMachineDefault describes a response with status code -1, with default header values.

Error
*/
type AbortReinstallMachineDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// Code gets the status code for the abort reinstall machine default response
func (o *AbortReinstallMachineDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this abort reinstall machine default response has a 2xx status code
func (o *AbortReinstallMachineDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this abort reinstall machine default response has a 3xx status code
func (o *AbortReinstallMachineDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this abort reinstall machine default response has a 4xx status code
func (o *AbortReinstallMachineDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this abort reinstall machine default response has a 5xx status code
func (o *AbortReinstallMachineDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this abort reinstall machine default response a status code equal to that given
func (o *AbortReinstallMachineDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *AbortReinstallMachineDefault) Error() string {
	return fmt.Sprintf("[POST /v1/machine/{id}/abort-reinstall][%d] abortReinstallMachine default  %+v", o._statusCode, o.Payload)
}

func (o *AbortReinstallMachineDefault) String() string {
	return fmt.Sprintf("[POST /v1/machine/{id}/abort-reinstall][%d] abortReinstallMachine default  %+v", o._statusCode, o.Payload)
}

func (o *AbortReinstallMachineDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *AbortReinstallMachineDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
