// Code generated by go-swagger; DO NOT EDIT.

package machine

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/metal-stack/metal-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// AvailableFirmwaresReader is a Reader for the AvailableFirmwares structure.
type AvailableFirmwaresReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AvailableFirmwaresReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAvailableFirmwaresOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAvailableFirmwaresDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAvailableFirmwaresOK creates a AvailableFirmwaresOK with default headers values
func NewAvailableFirmwaresOK() *AvailableFirmwaresOK {
	return &AvailableFirmwaresOK{}
}

/*AvailableFirmwaresOK handles this case with default header values.

OK
*/
type AvailableFirmwaresOK struct {
	Payload *models.V1AvailableFirmwares
}

func (o *AvailableFirmwaresOK) Error() string {
	return fmt.Sprintf("[GET /v1/machine/available-firmwares][%d] availableFirmwaresOK  %+v", 200, o.Payload)
}

func (o *AvailableFirmwaresOK) GetPayload() *models.V1AvailableFirmwares {
	return o.Payload
}

func (o *AvailableFirmwaresOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1AvailableFirmwares)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAvailableFirmwaresDefault creates a AvailableFirmwaresDefault with default headers values
func NewAvailableFirmwaresDefault(code int) *AvailableFirmwaresDefault {
	return &AvailableFirmwaresDefault{
		_statusCode: code,
	}
}

/*AvailableFirmwaresDefault handles this case with default header values.

Error
*/
type AvailableFirmwaresDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// Code gets the status code for the available firmwares default response
func (o *AvailableFirmwaresDefault) Code() int {
	return o._statusCode
}

func (o *AvailableFirmwaresDefault) Error() string {
	return fmt.Sprintf("[GET /v1/machine/available-firmwares][%d] availableFirmwares default  %+v", o._statusCode, o.Payload)
}

func (o *AvailableFirmwaresDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *AvailableFirmwaresDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
