// Code generated by go-swagger; DO NOT EDIT.

package machine

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/metal-stack/metal-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// AvailableBMCUpdatesReader is a Reader for the AvailableBMCUpdates structure.
type AvailableBMCUpdatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AvailableBMCUpdatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAvailableBMCUpdatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAvailableBMCUpdatesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAvailableBMCUpdatesOK creates a AvailableBMCUpdatesOK with default headers values
func NewAvailableBMCUpdatesOK() *AvailableBMCUpdatesOK {
	return &AvailableBMCUpdatesOK{}
}

/*AvailableBMCUpdatesOK handles this case with default header values.

OK
*/
type AvailableBMCUpdatesOK struct {
	Payload *models.V1MachineAvailableUpdates
}

func (o *AvailableBMCUpdatesOK) Error() string {
	return fmt.Sprintf("[GET /v1/machine/{id}/available-bmc-updates][%d] availableBMCUpdatesOK  %+v", 200, o.Payload)
}

func (o *AvailableBMCUpdatesOK) GetPayload() *models.V1MachineAvailableUpdates {
	return o.Payload
}

func (o *AvailableBMCUpdatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1MachineAvailableUpdates)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAvailableBMCUpdatesDefault creates a AvailableBMCUpdatesDefault with default headers values
func NewAvailableBMCUpdatesDefault(code int) *AvailableBMCUpdatesDefault {
	return &AvailableBMCUpdatesDefault{
		_statusCode: code,
	}
}

/*AvailableBMCUpdatesDefault handles this case with default header values.

Error
*/
type AvailableBMCUpdatesDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// Code gets the status code for the available b m c updates default response
func (o *AvailableBMCUpdatesDefault) Code() int {
	return o._statusCode
}

func (o *AvailableBMCUpdatesDefault) Error() string {
	return fmt.Sprintf("[GET /v1/machine/{id}/available-bmc-updates][%d] availableBMCUpdates default  %+v", o._statusCode, o.Payload)
}

func (o *AvailableBMCUpdatesDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *AvailableBMCUpdatesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
