// Code generated by go-swagger; DO NOT EDIT.

package machine

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/metal-stack/metal-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// FindIPMIMachinesReader is a Reader for the FindIPMIMachines structure.
type FindIPMIMachinesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindIPMIMachinesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindIPMIMachinesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewFindIPMIMachinesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewFindIPMIMachinesOK creates a FindIPMIMachinesOK with default headers values
func NewFindIPMIMachinesOK() *FindIPMIMachinesOK {
	return &FindIPMIMachinesOK{}
}

/*
FindIPMIMachinesOK describes a response with status code 200, with default header values.

OK
*/
type FindIPMIMachinesOK struct {
	Payload []*models.V1MachineIPMIResponse
}

// IsSuccess returns true when this find Ip m i machines o k response has a 2xx status code
func (o *FindIPMIMachinesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this find Ip m i machines o k response has a 3xx status code
func (o *FindIPMIMachinesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this find Ip m i machines o k response has a 4xx status code
func (o *FindIPMIMachinesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this find Ip m i machines o k response has a 5xx status code
func (o *FindIPMIMachinesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this find Ip m i machines o k response a status code equal to that given
func (o *FindIPMIMachinesOK) IsCode(code int) bool {
	return code == 200
}

func (o *FindIPMIMachinesOK) Error() string {
	return fmt.Sprintf("[POST /v1/machine/ipmi/find][%d] findIpMIMachinesOK  %+v", 200, o.Payload)
}

func (o *FindIPMIMachinesOK) String() string {
	return fmt.Sprintf("[POST /v1/machine/ipmi/find][%d] findIpMIMachinesOK  %+v", 200, o.Payload)
}

func (o *FindIPMIMachinesOK) GetPayload() []*models.V1MachineIPMIResponse {
	return o.Payload
}

func (o *FindIPMIMachinesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindIPMIMachinesDefault creates a FindIPMIMachinesDefault with default headers values
func NewFindIPMIMachinesDefault(code int) *FindIPMIMachinesDefault {
	return &FindIPMIMachinesDefault{
		_statusCode: code,
	}
}

/*
FindIPMIMachinesDefault describes a response with status code -1, with default header values.

Error
*/
type FindIPMIMachinesDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// Code gets the status code for the find IP m i machines default response
func (o *FindIPMIMachinesDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this find IP m i machines default response has a 2xx status code
func (o *FindIPMIMachinesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this find IP m i machines default response has a 3xx status code
func (o *FindIPMIMachinesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this find IP m i machines default response has a 4xx status code
func (o *FindIPMIMachinesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this find IP m i machines default response has a 5xx status code
func (o *FindIPMIMachinesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this find IP m i machines default response a status code equal to that given
func (o *FindIPMIMachinesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *FindIPMIMachinesDefault) Error() string {
	return fmt.Sprintf("[POST /v1/machine/ipmi/find][%d] findIPMIMachines default  %+v", o._statusCode, o.Payload)
}

func (o *FindIPMIMachinesDefault) String() string {
	return fmt.Sprintf("[POST /v1/machine/ipmi/find][%d] findIPMIMachines default  %+v", o._statusCode, o.Payload)
}

func (o *FindIPMIMachinesDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *FindIPMIMachinesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
