// Code generated by go-swagger; DO NOT EDIT.

package machine

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/metal-pod/metal-go/api/models"
)

// NewIPMIFindParams creates a new IPMIFindParams object
// with the default values initialized.
func NewIPMIFindParams() *IPMIFindParams {
	var ()
	return &IPMIFindParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIPMIFindParamsWithTimeout creates a new IPMIFindParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIPMIFindParamsWithTimeout(timeout time.Duration) *IPMIFindParams {
	var ()
	return &IPMIFindParams{

		timeout: timeout,
	}
}

// NewIPMIFindParamsWithContext creates a new IPMIFindParams object
// with the default values initialized, and the ability to set a context for a request
func NewIPMIFindParamsWithContext(ctx context.Context) *IPMIFindParams {
	var ()
	return &IPMIFindParams{

		Context: ctx,
	}
}

// NewIPMIFindParamsWithHTTPClient creates a new IPMIFindParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIPMIFindParamsWithHTTPClient(client *http.Client) *IPMIFindParams {
	var ()
	return &IPMIFindParams{
		HTTPClient: client,
	}
}

/*IPMIFindParams contains all the parameters to send to the API endpoint
for the ipmi find operation typically these are written to a http.Request
*/
type IPMIFindParams struct {

	/*Body*/
	Body *models.V1MachineFindRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the ipmi find params
func (o *IPMIFindParams) WithTimeout(timeout time.Duration) *IPMIFindParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ipmi find params
func (o *IPMIFindParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the ipmi find params
func (o *IPMIFindParams) WithContext(ctx context.Context) *IPMIFindParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ipmi find params
func (o *IPMIFindParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the ipmi find params
func (o *IPMIFindParams) WithHTTPClient(client *http.Client) *IPMIFindParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ipmi find params
func (o *IPMIFindParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the ipmi find params
func (o *IPMIFindParams) WithBody(body *models.V1MachineFindRequest) *IPMIFindParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the ipmi find params
func (o *IPMIFindParams) SetBody(body *models.V1MachineFindRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *IPMIFindParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
