// Code generated by go-swagger; DO NOT EDIT.

package machine

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/metal-stack/metal-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// ListIssuesReader is a Reader for the ListIssues structure.
type ListIssuesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListIssuesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListIssuesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListIssuesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListIssuesOK creates a ListIssuesOK with default headers values
func NewListIssuesOK() *ListIssuesOK {
	return &ListIssuesOK{}
}

/*
ListIssuesOK describes a response with status code 200, with default header values.

OK
*/
type ListIssuesOK struct {
	Payload []*models.V1MachineIssue
}

// IsSuccess returns true when this list issues o k response has a 2xx status code
func (o *ListIssuesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list issues o k response has a 3xx status code
func (o *ListIssuesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list issues o k response has a 4xx status code
func (o *ListIssuesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list issues o k response has a 5xx status code
func (o *ListIssuesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list issues o k response a status code equal to that given
func (o *ListIssuesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list issues o k response
func (o *ListIssuesOK) Code() int {
	return 200
}

func (o *ListIssuesOK) Error() string {
	return fmt.Sprintf("[GET /v1/machine/issues][%d] listIssuesOK  %+v", 200, o.Payload)
}

func (o *ListIssuesOK) String() string {
	return fmt.Sprintf("[GET /v1/machine/issues][%d] listIssuesOK  %+v", 200, o.Payload)
}

func (o *ListIssuesOK) GetPayload() []*models.V1MachineIssue {
	return o.Payload
}

func (o *ListIssuesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListIssuesDefault creates a ListIssuesDefault with default headers values
func NewListIssuesDefault(code int) *ListIssuesDefault {
	return &ListIssuesDefault{
		_statusCode: code,
	}
}

/*
ListIssuesDefault describes a response with status code -1, with default header values.

Error
*/
type ListIssuesDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// IsSuccess returns true when this list issues default response has a 2xx status code
func (o *ListIssuesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list issues default response has a 3xx status code
func (o *ListIssuesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list issues default response has a 4xx status code
func (o *ListIssuesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list issues default response has a 5xx status code
func (o *ListIssuesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list issues default response a status code equal to that given
func (o *ListIssuesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list issues default response
func (o *ListIssuesDefault) Code() int {
	return o._statusCode
}

func (o *ListIssuesDefault) Error() string {
	return fmt.Sprintf("[GET /v1/machine/issues][%d] listIssues default  %+v", o._statusCode, o.Payload)
}

func (o *ListIssuesDefault) String() string {
	return fmt.Sprintf("[GET /v1/machine/issues][%d] listIssues default  %+v", o._statusCode, o.Payload)
}

func (o *ListIssuesDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *ListIssuesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
