// Code generated by go-swagger; DO NOT EDIT.

package machine

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/metal-stack/metal-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// MachineCycleReader is a Reader for the MachineCycle structure.
type MachineCycleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MachineCycleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMachineCycleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewMachineCycleDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewMachineCycleOK creates a MachineCycleOK with default headers values
func NewMachineCycleOK() *MachineCycleOK {
	return &MachineCycleOK{}
}

/*
	MachineCycleOK describes a response with status code 200, with default header values.

OK
*/
type MachineCycleOK struct {
	Payload *models.V1MachineResponse
}

func (o *MachineCycleOK) Error() string {
	return fmt.Sprintf("[POST /v1/machine/{id}/power/cycle][%d] machineCycleOK  %+v", 200, o.Payload)
}
func (o *MachineCycleOK) GetPayload() *models.V1MachineResponse {
	return o.Payload
}

func (o *MachineCycleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1MachineResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMachineCycleDefault creates a MachineCycleDefault with default headers values
func NewMachineCycleDefault(code int) *MachineCycleDefault {
	return &MachineCycleDefault{
		_statusCode: code,
	}
}

/*
	MachineCycleDefault describes a response with status code -1, with default header values.

Error
*/
type MachineCycleDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// Code gets the status code for the machine cycle default response
func (o *MachineCycleDefault) Code() int {
	return o._statusCode
}

func (o *MachineCycleDefault) Error() string {
	return fmt.Sprintf("[POST /v1/machine/{id}/power/cycle][%d] machineCycle default  %+v", o._statusCode, o.Payload)
}
func (o *MachineCycleDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *MachineCycleDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
