// Code generated by go-swagger; DO NOT EDIT.

package machine

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/metal-stack/metal-go/api/models"
)

// NewTryAllocateMachineParams creates a new TryAllocateMachineParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTryAllocateMachineParams() *TryAllocateMachineParams {
	return &TryAllocateMachineParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTryAllocateMachineParamsWithTimeout creates a new TryAllocateMachineParams object
// with the ability to set a timeout on a request.
func NewTryAllocateMachineParamsWithTimeout(timeout time.Duration) *TryAllocateMachineParams {
	return &TryAllocateMachineParams{
		timeout: timeout,
	}
}

// NewTryAllocateMachineParamsWithContext creates a new TryAllocateMachineParams object
// with the ability to set a context for a request.
func NewTryAllocateMachineParamsWithContext(ctx context.Context) *TryAllocateMachineParams {
	return &TryAllocateMachineParams{
		Context: ctx,
	}
}

// NewTryAllocateMachineParamsWithHTTPClient creates a new TryAllocateMachineParams object
// with the ability to set a custom HTTPClient for a request.
func NewTryAllocateMachineParamsWithHTTPClient(client *http.Client) *TryAllocateMachineParams {
	return &TryAllocateMachineParams{
		HTTPClient: client,
	}
}

/* TryAllocateMachineParams contains all the parameters to send to the API endpoint
   for the try allocate machine operation.

   Typically these are written to a http.Request.
*/
type TryAllocateMachineParams struct {

	// Body.
	Body *models.V1MachineAllocateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the try allocate machine params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TryAllocateMachineParams) WithDefaults() *TryAllocateMachineParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the try allocate machine params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TryAllocateMachineParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the try allocate machine params
func (o *TryAllocateMachineParams) WithTimeout(timeout time.Duration) *TryAllocateMachineParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the try allocate machine params
func (o *TryAllocateMachineParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the try allocate machine params
func (o *TryAllocateMachineParams) WithContext(ctx context.Context) *TryAllocateMachineParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the try allocate machine params
func (o *TryAllocateMachineParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the try allocate machine params
func (o *TryAllocateMachineParams) WithHTTPClient(client *http.Client) *TryAllocateMachineParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the try allocate machine params
func (o *TryAllocateMachineParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the try allocate machine params
func (o *TryAllocateMachineParams) WithBody(body *models.V1MachineAllocateRequest) *TryAllocateMachineParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the try allocate machine params
func (o *TryAllocateMachineParams) SetBody(body *models.V1MachineAllocateRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *TryAllocateMachineParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
