// Code generated by go-swagger; DO NOT EDIT.

package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/metal-stack/metal-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// FindImageReader is a Reader for the FindImage structure.
type FindImageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindImageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindImageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewFindImageDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewFindImageOK creates a FindImageOK with default headers values
func NewFindImageOK() *FindImageOK {
	return &FindImageOK{}
}

/*
FindImageOK describes a response with status code 200, with default header values.

OK
*/
type FindImageOK struct {
	Payload *models.V1ImageResponse
}

// IsSuccess returns true when this find image o k response has a 2xx status code
func (o *FindImageOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this find image o k response has a 3xx status code
func (o *FindImageOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this find image o k response has a 4xx status code
func (o *FindImageOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this find image o k response has a 5xx status code
func (o *FindImageOK) IsServerError() bool {
	return false
}

// IsCode returns true when this find image o k response a status code equal to that given
func (o *FindImageOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the find image o k response
func (o *FindImageOK) Code() int {
	return 200
}

func (o *FindImageOK) Error() string {
	return fmt.Sprintf("[GET /v1/image/{id}][%d] findImageOK  %+v", 200, o.Payload)
}

func (o *FindImageOK) String() string {
	return fmt.Sprintf("[GET /v1/image/{id}][%d] findImageOK  %+v", 200, o.Payload)
}

func (o *FindImageOK) GetPayload() *models.V1ImageResponse {
	return o.Payload
}

func (o *FindImageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ImageResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindImageDefault creates a FindImageDefault with default headers values
func NewFindImageDefault(code int) *FindImageDefault {
	return &FindImageDefault{
		_statusCode: code,
	}
}

/*
FindImageDefault describes a response with status code -1, with default header values.

Error
*/
type FindImageDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// IsSuccess returns true when this find image default response has a 2xx status code
func (o *FindImageDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this find image default response has a 3xx status code
func (o *FindImageDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this find image default response has a 4xx status code
func (o *FindImageDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this find image default response has a 5xx status code
func (o *FindImageDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this find image default response a status code equal to that given
func (o *FindImageDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the find image default response
func (o *FindImageDefault) Code() int {
	return o._statusCode
}

func (o *FindImageDefault) Error() string {
	return fmt.Sprintf("[GET /v1/image/{id}][%d] findImage default  %+v", o._statusCode, o.Payload)
}

func (o *FindImageDefault) String() string {
	return fmt.Sprintf("[GET /v1/image/{id}][%d] findImage default  %+v", o._statusCode, o.Payload)
}

func (o *FindImageDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *FindImageDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
