name: build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install golangci-lint
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.27.0

    - name: Run golangci-lint
      run: $(go env GOPATH)/bin/golangci-lint run

    - name: Build
      run: make test
    
    - name: Publish Codecoverage report
      run: bash <(curl -s https://codecov.io/bash)
