name: build

on:
  push

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: false

    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        args: -p bugs -p unused

    - name: Build
      run: make test

    - name: Publish Codecoverage report
      run: bash <(curl -s https://codecov.io/bash)
